### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by Caet-pip** [tomaarsen/attention_sinks#12]
When running this code to import the model:

from attention_sinks import AutoModel
model = AutoModel.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1", device_map="auto")

I get this error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[/Users/fawazahamedshaik/Documents/RAG/GRails.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/fawazahamedshaik/Documents/RAG/GRails.ipynb) Cell 31 line 1
----> [1](vscode-notebook-cell:/Users/fawazahamedshaik/Documents/RAG/GRails.ipynb#X63sZmlsZQ%3D%3D?line=0) from attention_sinks import AutoModel
      [3](vscode-notebook-cell:/Users/fawazahamedshaik/Documents/RAG/GRails.ipynb#X63sZmlsZQ%3D%3D?line=2) model = AutoModel.from_pretrained("meta-llama/Llama-2-7b-hf", device_map="auto")

File [/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/attention_sinks/__init__.py:6](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/attention_sinks/__init__.py:6)
      3 from transformers import AutoTokenizer
      5 from .attention_sink_kv_cache import AttentionSinkKVCache
----> 6 from .models import (
      7     AutoModel,
      8     AutoModelForCausalLM,
      9     AutoModelForQuestionAnswering,
     10     AutoModelForSequenceClassification,
     11     AutoModelForTokenClassification,
     12     FalconForCausalLM,
     13     FalconForQuestionAnswering,
     14     FalconForSequenceClassification,
     15     FalconForTokenClassification,
     16     FalconModel,
     17     FalconPreTrainedModel,
     18     GPTNeoXForCausalLM,
     19     GPTNeoXForQuestionAnswering,
     20     GPTNeoXForSequenceClassification,
     21     GPTNeoXForTokenClassification,
...
   (...)
     36     FalconModel,
     37 )

ImportError: cannot import name 'MistralConfig' from 'transformers' (/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/__init__.py)

**Comment by tomaarsen** [comment]
Hello!

`MistralConfig` was only added to `transformers` very recently, in version `4.34.0`. You must install this version:
```
pip install transformers==4.34.0
```

Hope this helps!

- Tom Aarsen
